export enum TRACKING_STATUS {
  PENDING = 'PENDING',
  RECIEVED = 'RECIEVED',
  ON_THE_WAY = 'ON THE WAY',
  NEAREST_CENTER = 'NEAREST CENTER',
  DELIVERED = 'DELIVERED',
}

export enum ROLE {
  ADMIN = 'ADMIN',
  USER = 'USER',
}
